server:
  port: 8080
spring:
  application:
    name: "CrediYa"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  datasource:
    url: "jdbc:h2:mem:test"
    username: "sa"
    password: "pass"
    driverClassName: "org.h2.Driver"
  r2dbc:
    url: "r2dbc:postgresql://postgres:admin@localhost:5432/crediya_db"
    host: "localhost"
    port: "5432"
    database: "crediya_db"
    schema: "public"
    username: "postgres"
    password: "admin"
springdoc:
  swagger-ui:
    enabled: true
    path: "/swagger-ui.html"
  api-docs:
    path: "/v3/api-docs"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
